---
name: Build Offical OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  THEME_ARGON: true
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Get Latest Version From Official Release
      run: |
        echo "LATESTTAG=$(curl -Ls -o /dev/null -w %{url_effective} \
        https://github.com/openwrt/openwrt/releases/latest | \
        awk -F '/' '{ print $NF }' | cut -c 2-)" >> $GITHUB_ENV

    - name: Download Image Builder From Official Release
      id: downloadLatestImageBuilder
      run: |
        wget -q https://downloads.openwrt.org/releases/${{ env.LATESTTAG }}/targets/ramips/mt7620/openwrt-imagebuilder-${{ env.LATESTTAG }}-ramips-mt7620.Linux-x86_64.tar.xz && \
        echo "::set-output name=ib-file-exist::true" || echo "::set-output name=ib-file-exist::false"

    - name: Decompress Image Builder
      if: steps.downloadLatestImageBuilder.outputs.ib-file-exist == 'true'
      run: |
        tar -Jxf openwrt-imagebuilder-*.tar.xz

    - name: Build Firmware
      id: build
      if: steps.downloadLatestImageBuilder.outputs.ib-file-exist == 'true'
      run: |
        cd openwrt-imagebuilder-*/
        echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV
        make -j $(nproc) image PROFILE=edimax_br-6478ac-v2 \
        PACKAGES="-ppp -ppp-mod-pppoe -ip6tables -odhcp6c -kmod-pppoe -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only \
        uhttpd uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-app-opkg luci-mod-admin-full \
        luci-theme-bootstrap openvswitch cjson" && \
        echo "::set-output name=build-success::true" || echo "::set-output name=build-success::false"
        echo "::set-output name=done-time::$(date +%s)"

    - name: Upload Bin Directory
      if: steps.build.outputs.build-success == 'true'
      uses: actions/upload-artifact@master
      with:
        name: openwrt-bin-directory
        path: ${{ env.OPENWRTROOT }}/bin

    - name: Upload firmware to release
      if: steps.build.outputs.build-success == 'true'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.LATESTTAG }}-${{ steps.build.outputs.done-time }}
        files: |
          ${{ env.OPENWRTROOT }}/bin/targets/*/*/*.bin
          ${{ env.OPENWRTROOT }}/bin/targets/*/*/*.manifest
          ${{ env.OPENWRTROOT }}/bin/targets/*/*/sha256sums
